// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: days.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDay = `-- name: CreateDay :one
INSERT INTO days (id, name, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, user_id, created_at, updated_at
`

type CreateDayParams struct {
	ID        uuid.UUID
	Name      string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateDay(ctx context.Context, arg CreateDayParams) (Day, error) {
	row := q.db.QueryRowContext(ctx, createDay,
		arg.ID,
		arg.Name,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Day
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
