// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: exercises.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (id, name, muscle, repetitions, instructions, day_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, muscle, repetitions, instructions, day_id, created_at, updated_at
`

type CreateExerciseParams struct {
	ID           uuid.UUID
	Name         string
	Muscle       string
	Repetitions  int32
	Instructions string
	DayID        uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise,
		arg.ID,
		arg.Name,
		arg.Muscle,
		arg.Repetitions,
		arg.Instructions,
		arg.DayID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Muscle,
		&i.Repetitions,
		&i.Instructions,
		&i.DayID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
