// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, password, hostname, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, password, created_at, updated_at, hostname
`

type CreateUserParams struct {
	ID        uuid.UUID
	Username  sql.NullString
	Password  sql.NullString
	Hostname  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.Hostname,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hostname,
	)
	return i, err
}

const getUserByHostname = `-- name: GetUserByHostname :one
SELECT id, username, password, created_at, updated_at, hostname FROM users WHERE hostname = $1
`

func (q *Queries) GetUserByHostname(ctx context.Context, hostname sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByHostname, hostname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hostname,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, created_at, updated_at, hostname FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Hostname,
	)
	return i, err
}
